apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: ghcr.io/mikecarter-dev/container-test:latest
          name: hello-world
